{% set version = "1.2.0" %}

package:
  name: typed-ast
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/typed-ast/typed-ast-{{ version }}.tar.gz
  sha256: b4726339a4c180a8b6ad9d8b50d2b6dc247e1b79b38fe2290549c98e82e4fd15

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - typed_ast

about:
  home: https://github.com/python/typed_ast
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: a fork of Python 2 and 3 ast modules with type comment support
  description: |
    typed_ast is a Python 3 package that provides a Python 2.7 and Python 3
    parser similar to the standard ast library. Unlike ast, the parsers in
    typed_ast include PEP 484 type comments and are independent of the version
    of Python under which they are run. The typed_ast parsers produce the
    standard Python AST (plus type comments), and are both fast and correct, as
    they are based on the CPython 2.7 and 3.6 parsers.
  doc_url: https://github.com/python/typed_ast/blob/master/README.md
  dev_url: https://github.com/python/typed_ast

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
